### ISSUE TITLE
[🐞] Optimizer should find all qrls inside qrls even when only building for client or server

### ISSUE THREAD

**Issue by mhevery** [QwikDev/qwik#3189]
### Which component is affected?

Qwik Runtime

### Describe the bug

```
6:04:20 PM [vite] Internal server error: invoke: qrl $captureRef$ must be defined inside useLexicalScope()
  File: /home/projects/qwik-starter-ydb5i8/src/routes/index.tsx:17:48
      at createError (file://file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik/core.mjs:163:17)
      at logError (file://file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik/core.mjs:157:54)
      at logErrorAndStop (file://file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik/core.mjs:167:17)
      at assertDefined (file://file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik/core.mjs:407:15)
      at Proxy.useLexicalScope (file://file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik/core.mjs:4991:9)
      at eval (/home/projects/qwik-starter-ydb5i8/src/routes/index.tsx:17:48)
      at invoke (file://file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik/core.mjs:1420:26)
      at eval (file://file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik/core.mjs:6776:35)
      at async invokeQRL (file://file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik/core.mjs:6795:24)
      at async pureServerFunction (file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik-city/vite/index.cjs:23722:26)
      at async Object.next (file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik-city/vite/index.cjs:23930:9)
      at async runNext (file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik-city/vite/index.cjs:24128:5)
      at async eval (file:///home/projects/qwik-starter-ydb5i8/node_modules/@builder.io/qwik-city/vite/index.cjs:24537:26)
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-ydb5i8?file=src%2Froutes%2Findex.tsx,package.json

### System Info

```shell
n/a
```

**Comment by gioboa** [comment]
I tested the repo with Qwik `1.2.10` and it fails.
`const capitalize = $((v: string) => v[0].toUpperCase() + v.substring(1));` is breaking the system.
is it a priority task?

**Comment by mhevery** [comment]
It would be nice to fix....

**Comment by wmertens** [comment]
Ok, so this is actually because the server$ gets eliminated too early because the onClick$ is only built for the server, which is more visible in #6871.
