### ISSUE TITLE
[🐞] The specified module could not be found - qwik.win32-x64-msvc.node

### ISSUE THREAD

**Issue by dinhtheloc** [QwikDev/qwik#3704]
### Which component is affected?

Qwik Runtime

### Describe the bug

**Describe the bug**

After I run the command "npm create qwik@latest" and install node_modules.
I'm getting errors after running "npm start". 

```
PS D:\work\qwik\qwik-app> npm start

> my-qwik-library-name@0.0.1 start
> vite --open --mode ssr

Error: The specified module could not be found.
\\?\D:\work\qwik\qwik-app\node_modules\@builder.io\qwik\bindings\qwik.win32-x64-msvc.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadPlatformBinding (file:///D:/work/qwik/qwik-app/node_modules/@builder.io/qwik/optimizer.mjs:520:73)
    at async createOptimizer (file:///D:/work/qwik/qwik-app/node_modules/@builder.io/qwik/optimizer.mjs:576:48)
    at async Object.init (file:///D:/work/qwik/qwik-app/node_modules/@builder.io/qwik/optimizer.mjs:944:47)
    at async config (file:///D:/work/qwik/qwik-app/node_modules/@builder.io/qwik/optimizer.mjs:1995:7)
    at async runConfigHook (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:64005:25) {
  code: 'ERR_DLOPEN_FAILED'
}

  VITE v4.2.1  ready in 433 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Missing "./src/counter_component_eh4rwzf8mbu.js" specifier in "my-qwik-library-name" package
Missing "./src/logo_component_t5jxal1aopo.js" specifier in "my-qwik-library-name" package
2:43:57 PM [vite] Error when evaluating SSR module /src/root.tsx:

2:43:57 PM [vite] Error when evaluating SSR module D:/work/qwik/qwik-app/src/entry.ssr.tsx:

2:43:57 PM [vite] Internal server error: Missing "./src/counter_component_eh4rwzf8mbu.js" specifier in "my-qwik-library-name" package
  Plugin: vite:import-analysis
  File: D:/work/qwik/qwik-app/src/components/counter/counter.tsx
      at e (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:16076:25)
      at n (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:16076:627)
      at o (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:16076:1297)
      at resolveExportsOrImports (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:23295:20)
      at resolveDeepImport (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:23314:31)
      at tryNodeResolve (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:23000:20)
      at Context.resolveId (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:22762:28)
      at Object.resolveId (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:43314:46)
      at async TransformContext.resolve (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:43043:23)
      at async normalizeUrl (file:///D:/work/qwik/qwik-app/node_modules/vite/dist/node/chunks/dep-79892de8.js:41370:34)
```

D:\work\qwik\qwik-app\node_modules\@builder.io\qwik\bindings\qwik.win32-x64-msvc.node
I checked and confirmed qwik.win32-x64-msvc.node existed in the node_modules folder.
I feel weird why the path includes \\?\... qwik.win32-x64-msvc.node
I don't know what's going on!

### Reproduction

https://github.com/dinhtheloc/qwik-demo

### Steps to reproduce

npm run start

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 7.82 GB / 15.84 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: 0.101.0 => 0.101.0
    undici: 5.21.0 => 5.21.0
    vite: 4.2.1 => 4.2.1
```

**Comment by Rillwz** [comment]
I got similar error, can't inspect where exactly made this.

`> start
> vite --open --mode ssr

Error: The specified module could not be found.
\\?\C:\Users\yusri\qwik-app\node_modules\@builder.io\qwik\bindings\qwik.win32-x64-msvc.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at sys.dynamicImport (C:\Users\yusri\qwik-app\node_modules\@builder.io\qwik\optimizer.cjs:1197:35)
    at loadPlatformBinding (C:\Users\yusri\qwik-app\node_modules\@builder.io\qwik\optimizer.cjs:1280:37)
    at createOptimizer (C:\Users\yusri\qwik-app\node_modules\@builder.io\qwik\optimizer.cjs:1358:93)
    at async Object.init2 [as init] (C:\Users\yusri\qwik-app\node_modules\@builder.io\qwik\optimizer.cjs:1722:49)
    at async config (C:\Users\yusri\qwik-app\node_modules\@builder.io\qwik\optimizer.cjs:3085:9) {
  code: 'ERR_DLOPEN_FAILED'
}`

**Comment by sapphi-red** [comment]
This "ERR_DLOPEN_FAILED The specified module could not be found." error happens when you're missing a required DLL. Usually the one missing is `msvcp140.dll` included in Microsoft Visual C++ Redistributable. You can download it from https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by PatrickJS** [comment]
closing since this is windows dll issue
