### ISSUE TITLE
[🐞] fetching public folder not working with SSG

### ISSUE THREAD

**Issue by GrandSchtroumpf** [QwikDev/qwik#4222]
### Which component is affected?

Qwik Runtime

### Describe the bug

My app is storing data from ethereum and aggregating them into json files with a Github Action cron every day.
I want this data to be public for any developer to access it with a GET, and I want to build my with SSG because data is synced everyday only.

I'm fetching some data from the public folder : 
```jsx
export default component$(() => {
  const loc = useLocation();
  const list = useResource$(() => {
    const url = `${loc.url.origin}/list.json`;
    return fetch(url).then((v) => v.json());
  });
  return <Resource value={list} onResolved={(items) => (
    <ul>
      {items.map((item: { id: string }) => (
      <li key={item.id}>{item.id}</li>
      ))}
   </ul>
  )}/>
});
```
But when I build it with SSG it breaks because fetch fails.
I understand that SSG runs inside a node process, so there is no http server to fetch, but still I think the expected behavior should be for it to work.

### Reproduction

https://stackblitz.com/edit/qwik-starter-toe9wd?file=src/routes/index.tsx

### Steps to reproduce

The link above already have the SSG adapter.
`npm run build`

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 18.39 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1095.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ~1.1.1 => 1.1.2
    @builder.io/qwik-city: ~1.1.1 => 1.1.2
    undici: ^5.22.0 => 5.22.1
    vite: ^4.3.5 => 4.3.5
```

### Additional Information
As a side note, when I run `npm start` I've got this message : 
```
files in the public directory are served at the root path.
Instead of /public/list.json, use /list.json
```
But use

**Comment by GrandSchtroumpf** [comment]
Here is the error message btw : 
```
Error during SSG
fetch failed
  Pathname: /chains/
  Plugin: qwik-ssg
  File: /....../dist/.../server/assets/index.qwik-9dc8e058.mjs:9:57183
      at Object.fetch (node:internal/deps/undici/undici:11457:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.h (file:///....../dist/....../server/assets/index.qwik-9dc8e058.mjs:9:57183)
      at async Promise.all (index 0)
      at async file:///....../node_modules/@builder.io/qwik-city/middleware/request-handler/index.mjs:378:7
      at async Object.next (file:///C:/code/qwik/qwik-eth/node_modules/@builder.io/qwik-city/middleware/request-handler/index.mjs:773:9)
      at async runNext (file:///....../node_modules/@builder.io/qwik-city/middleware/request-handler/index.mjs:1014:5)
[Error: Error while running SSG from "static-generate" adapter. At least one path failed to render.] {
  code: 'PLUGIN_ERROR',
  plugin: 'vite-plugin-qwik-city-static-generate',
  hook: 'closeBundle'
}
```

**Comment by GrandSchtroumpf** [comment]
Sorry, for spamming. After investigating a little, it seems that it's not related to the origin because the static adapter add the origin... I didn't find the source of the error yet, but here is my workaround using `fs` just in case : 
```typescript
export async function getStaticJson<T>(req: {url: URL}, path: string): Promise<T> {
  const origin = req.url.origin;
  // This origin is set in the vite.config.ts
  if (origin !== 'https://__ssg__.com') {
    const url = `${req.url.origin}/${path}`;
    return fetch(url).then(v => v.json());
  } else {
    const file = await fs.readFile(join(publicFolder, path), 'utf8');
    return JSON.parse(file);
  }
}
```
And it's used like that : 
```typescript
export const useChain = routeLoader$((req) => getStaticJson(req, 'list.json'));
// Or
const list = useResource$(() => getStaticJson(loc, 'list.json'));
```

**Comment by PatrickJS** [comment]
this works but on the server you need the full url and on the client you don't
