### ISSUE TITLE
[🐞] Support Typescript "moduleResolution": "node16" and "bundler"

### ISSUE THREAD

**Issue by ziimakc** [QwikDev/qwik#4689]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

When using esm import `.js` or `.jsx` extensions is required. Trying to follow this requirement qwik fails to build with the following error:
```
Could not resolve "./components/router-head/router-head.jsx" from "src/s_qn6vsz8sp28.js"

error during build:
RollupError: Could not resolve "./components/router-head/router-head.jsx" from "src/s_qn6vsz8sp28.js"
    at error (file:///home/app/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:2213:30)
    at ModuleLoader.handleInvalidResolvedId (file:///home/app/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:24219:24)
    at file:///home/app/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:24181:26
```
```
// root.tsx
import { RouterHead } from "./components/router-head/router-head.jsx";
```

### Reproduction

- `git clone https://github.com/ZiiMakc/temp`
- `npm install`
- `npm run build`

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 5.29 GB / 7.68 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/bin/node
    npm: 9.5.1 - /usr/bin/npm
```

**Comment by manucorporat** [comment]
> When using esm import .js or .jsx extensions is required

Not sure i understand

**Comment by manucorporat** [comment]
Tried and it works, can you provide a full repo that reprodices the issue?

**Comment by ZiiMakc** [comment]
@manucorporat 

Here is example

- `git clone https://github.com/ZiiMakc/temp`
- `npm install`
- `npm run build`

**Comment by ZiiMakc** [comment]
Probably related: https://github.com/rollup/rollup/issues/4917

**Comment by ZiiMakc** [comment]
See also https://github.com/vitejs/vite/issues/8993

**Comment by ZiiMakc** [comment]
Temporary solution:
```
import { defineConfig } from "vite";
import { qwikVite } from "@builder.io/qwik/optimizer";
import { qwikCity } from "@builder.io/qwik-city/vite";
import pluginTypescript from "@rollup/plugin-typescript";

export default defineConfig(() => {
  return {
    plugins: [qwikCity(), qwikVite()],
    build: {
      rollupOptions: {
        plugins: [pluginTypescript()],
      },
    },
  };
});
```

Also remove `outDir` and `declaration` from `tsconfig`

**Comment by octet-stream** [comment]
I have the same issue. Here's minimal repro on StackBlitz: https://stackblitz.com/edit/qwik-starter-rfjklh?file=src%2Froot.tsx

Just run `npm run build` in the terminal and you'll get the error.

**Comment by octet-stream** [comment]
From what I can tell it is possible to use `.js` extensions when importing modules within .ts files. At least this is possible for server-side code. You can see that in `src/routes/plugin.ts` file: if you remove `.js` from `src/root.tsx`, but keep one in `src/routes/plugin.tsx` then `npm run build` will build the project successfully. I have tried to import the same file (`src/lib/add`) in home page module. It shows the error even with `npm run dev` if I use `add` function imported from this module in `useTask$`. On the server this code will be imported and executed without any problem, but then on the client it doesn't work.

**Comment by PatrickJS** [comment]
this seems to work now as we are on different TypeScript version and node requirement now. please make a new issue if there is still an issue

**Comment by octet-stream** [comment]
@PatrickJS is there any estimate date for this fix to be released? Because I still get the same error in 1.5.3, so it's not fixed yet.

**Comment by octet-stream** [comment]
Sure, here you go: https://github.com/octet-stream/qwik-typescript-js-extension-issue

**Comment by PatrickJS** [comment]
well it's `.tsx` and you need `allowImportingTsExtensions: true` in tsconfig

**Comment by PatrickJS** [comment]
oh yeah I see there were changing in tsconfig. I don't know enough about TypeScript to help with this maybe someone else can

**Comment by PatrickJS** [comment]
yeah the quick fix might be a plugin to remap the .js to the correct files before qwik takes over

**Comment by ziimakc** [comment]
For anyone who want to use proper `.js` extension, install `@rollup/plugin-typescript` and use following config as example:

tsconfig.json
```
{
	"extends": "../../other/tsconfig.base.json",
	"compilerOptions": {
		"target": "ES2022",
		"module": "ES2022",
		"lib": ["es2022", "DOM", "WebWorker", "DOM.Iterable"],
		"jsx": "react-jsx",
		"jsxImportSource": "@builder.io/qwik",
		"moduleResolution": "Bundler",
		"esModuleInterop": true,
		"incremental": true,
		"outDir": "dist",
		"noEmit": true
	},
	"include": ["src", "./*.d.ts", "./*.config.ts"]
}
```

vite.config.ts:
```
import { qwikCity } from "@builder.io/qwik-city/vite";
import { qwikVite } from "@builder.io/qwik/optimizer";
import pluginTypescript from "@rollup/plugin-typescript";
import { defineConfig, type UserConfig } from "vite";

export default defineConfig(({ command, mode }): UserConfig => {
	const config: UserConfig = {
		plugins: [qwikCity(), qwikVite()],
		build: {
			rollupOptions: {
				plugins: [pluginTypescript()],
			},
		},
	};

	return config;
});
```

**Comment by wmertens** [comment]
I don't understand, doesn't ts-node look at tsconfig? We recommend using module resolution Bundler.

**Comment by wmertens** [comment]
@ziimakc is this still happening in 1.8.0?

**Comment by octet-stream** [comment]
> I don't understand, doesn't ts-node look at tsconfig? We recommend using module resolution Bundler.

ts-node does not do anything with paths, because TS itself keeps paths untouched. It just keeps them as-is. But in order to ESM to work in Node.js, I need to use the `.js` specifier, which Qwik (or rather Rollup, as far as I see from this conversation) cannot compile when targeting production build. I got the same error, with the same file (router-head).

I just tried 1.9.0 and the issue is still in the effect.

----

Also, I can see a new issue: TypeScript seem to have problems picking up JSX types (see the screenshot) when I use the same `tsconfig.json` as in the repo I linked above in one of my comments.

<details>
<summary>Details</summary>

<img width="715" alt="image" src="https://github.com/user-attachments/assets/c0e87ea8-9614-4b7c-82a8-5c2dc3fc589e">


</details>

I see the same problem at least in v1.5.3 (which is the same version from the respo I linked above) and above. It seem to cover the whole `InristicElements` namespace. But this probably have to be separated into different issue. Are JSX type from Qwik compatible with `node16`? I don't have this issue with Remix for example, so types from *React* are compatible.

**Comment by octet-stream** [comment]
Had to mention that as far as I remember, this problem only affects client-side of a bundle. Server-side code runs with `.js` specifier just fine, so I ended up just keeping moduleResolution set to `Bundler` and using the specifier only for server code until the issue is resolved (because, as I said, otherwise my code cannot be consumed by Node.js when I run it via ts-node). This is not consistent and I had to remember to use it on the server and keep track on which files will be referenced by Mikro ORM config. When `moduleResolution` is set to `node16` tsc will require `.js` specifier at every absolute and relative path, so if I forgot one - my code won't compile and VSCode will also show me an error (and suggest `.js` when I write paths) which is to be expected.

**Comment by octet-stream** [comment]
@wmertens a friendly reminder that this one is still relevant too :)
I just tested it locally on a fresh project created with `pnpm create qwik@latest` and changed `moduleResolution` and `module` in `tsconfig.json` to `node16` and resolution breaks, but this time on type-level: I am able to *build* my project now if I remove `build.types` script. VSCode is also unable to pick up any types from Qwik.

<img width="760" height="611" alt="Image" src="https://github.com/user-attachments/assets/7069bae8-bd0c-4ffc-98a3-7cd19da7e05f" />

**Comment by octet-stream** [comment]
Can also confirm that I am able to build project when I have [`allowImportingTsExtensions`](https://www.typescriptlang.org/tsconfig/#allowImportingTsExtensions) option enabled and use `.ts` (including `.tsx` and others) in module specifier. So the issue only remains on type resolution level.

**Comment by wmertens** [comment]
Ok so we need to fix our package so that node16 resolution works for types. Urgh.
