### ISSUE TITLE
[🐞] Optimizer Issue: "implicit$FirstArg" Functionality Error

### ISSUE THREAD

**Issue by devcaeg** [QwikDev/qwik#5251]
### Which component is affected?

Qwik Optimizer (rust)

### Describe the bug

There is an issue with the Qwik optimizer. This problem did not occur in previous versions, though I can't specify from which version it started. When trying to execute a function wrapped in "implicit$FirstArg", the following error message appears: "**Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.**" This error prevents the application from continuing to run.

This error is affecting libraries like ModularForms by the creator @fabian-hiller. Although there's an issue (fabian-hiller/modular-forms#135) opened in the ModularForms repository, the root of the problem lies in Qwik.

### Reproduction

https://stackblitz.com/edit/qwik-starter-juwwvd?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Click on the reproduction link
2. Execute "npm install && npm run dev"
3. Wait a few seconds and the error will appear in the console

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 187.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
    Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 17.0
  npmPackages:
    @builder.io/qwik: 1.2.12 => 1.2.12 
    @builder.io/qwik-city: 1.2.12 => 1.2.12 
    undici: 5.25.2 => 5.25.2 
    vite: 4.4.9 => 4.4.9
```

### Additional Information

The error in StackBlitz differs slightly from a local execution. In local mode (development mode), the error is displayed in both the console and the browser screen. However, in StackBlitz, the error appears in the console with a different message and prevents the project from starting.

**Comment by mhevery** [comment]
I get this errer instead:

```
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/home/projects/qwik-starter-juwwvd/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:10169:19)
    at eval (/home/projects/qwik-starter-juwwvd/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55782:25)
    at eval (/home/projects/qwik-starter-juwwvd/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55773:21)
    at ssrRewriteStacktrace (/home/projects/qwik-starter-juwwvd/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55772:10)
    at ssrFixStacktrace (/home/projects/qwik-starter-juwwvd/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55825:24)
    at Object.ssrFixStacktrace (/home/projects/qwik-starter-juwwvd/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:65006:13)
    at eval (/home/projects/qwik-starter-juwwvd/node_modules/@builder.io/qwik/optimizer.cjs:2897:18)
 ```

**Comment by mhevery** [comment]
Could you help us by bisecting which change is causing the issue.

You can install `@builder.io/qwik` from https://github.com/BuilderIO/qwik-build. Edit `package.json`
```
"@builder.io/qwik": "github:BuilderIo/qwik-build#SHA",
```

Where the `SHA` is a specific `SHA` from https://github.com/BuilderIO/qwik-build In this way you could help us a lot.

**Comment by devcaeg** [comment]
Hi @mhevery,

Yes, the error "Error: `line` must be greater than 0 (lines start at line 1)..." is the one that appears in Stackblitz, which for some reason is different from the one that appears running the project locally.

**Comment by devcaeg** [comment]
@mhevery 

I've pinpointed the source of the error, and it appears to be an issue that has been present for some time. The problem emerges starting from version "0.19.0" with the message: ```[vite] Internal server error: Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.```

The immediately preceding version, "0.18.1", as well as its predecessors, display a different error but linked to the same code. The associated error messages are:

```[vite] Internal server error: Reference to identifier declared at the root 'test$'. It needs to be exported in order to be used inside a Qrl($) scope.```

```[vite] Internal server error: Found 'test$' but did not find the corresponding 'testQrl' exported in the same file. Please ensure it is exported and spelled correctly.```

In summary, from version "0.19.0" onwards, I encounter the same error, whereas in versions prior to "0.19.0", I come across two different errors.

**Comment by devcaeg** [comment]
@mhevery 

Upon further investigation, I determined that the error ```[vite] Internal server error: Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.``` appears starting from this [commit](https://github.com/BuilderIO/qwik-build/commit/e034a69b58a02ed35559a396dce2be1d45281d16) in "qwik-build". For some reason, this commit introduces the issue. In the preceding [commit](https://github.com/BuilderIO/qwik-build/commit/7787c53a4d552e7f3a8ee5bfa236cb1926a19718), the aforementioned error doesn't show up, but the other two previously mentioned errors do.

**Comment by mhevery** [comment]
WOW, that is a very old commit...

**Comment by devcaeg** [comment]
I've updated the issue reproduction on [StackBlitz](https://stackblitz.com/edit/qwik-starter-juwwvd?file=src%2Froutes%2Findex.tsx). When running "npm run dev", the error is displayed. However, when using "npm run preview", there is no error, but the code doesn't execute fully, as evidenced by some clear console.log (the god of debugging 🤪) messages.

**Comment by devcaeg** [comment]
Any news on this issue?

**Comment by gioboa** [comment]
This issue is really old, is it still valid?

**Comment by wmertens** [comment]
@devcaeg  The problem is that you didn't add Qrl to the name, and didn't export the functions:

```ts
function test(action: QRL<() => string>): QRL<() => void> {
  console.log('Test 2');

  return $(async () => {
    console.log('Test 3');

    await action();
  });
}

const test$ = implicit$FirstArg(test);
```

You should name the wrapped function `testQrl`. Then it will work.

https://qwik.dev/playground/#f=Q0o0xhZmiIgCR0xgkI8OUkLQAdW2wMydWaLilllUXOJYBIxBohIVPApKgIVwYFGORiKYawWywQYSKJD2gZ2mFTSQyvIzU8AhhVyLq4cA9SsYqQPdjghDSOGCCFpsWoyhWhSgFQTEfg2goIICMBRq0aIL5EwVYHxh%2BFcD6gGQacRkGLBBUL5SRqaS5mgmGoaZCAA
