### ISSUE TITLE
[🐞] plugin:vite:esbuild] [plugin vite:esbuild] src/components/router-head/router-head.tsx: Duplicate key "dangerouslySetInnerHTML"

### ISSUE THREAD

**Issue by notcod** [QwikDev/qwik#6119]
### Which component is affected?

Qwik Runtime

### Describe the bug

Fresh `npm create qwik@latest`
```
[plugin:vite:esbuild] [plugin vite:esbuild] src/components/router-head/router-head.tsx: Duplicate key "dangerouslySetInnerHTML" in object literal
40 |                          return s.style;
41 |                      },
42 |                      dangerouslySetInnerHTML: _wrapSignal(s, "style")
   |                      ^
43 |                  }, null, 0, s.key))
44 |          ]
```
warning is in "@builder.io/qwik": "1.5.2",
in version 1.5.1 there is no warning

### Reproduction

/

### System Info

```shell
/
```

**Comment by ohkimur** [comment]
I have the same issue after the last update.

**Comment by genki** [comment]
@ohkimur 
Me too.

**Comment by notcod** [comment]
I also have error with code I used to write before without problems:

```
export const SomeComponent = component$(() => {
  const ACTION = useSomeAction();
  useVisibleTask$(({ track, cleanup }) => {
    track(() => ACTION.value);
    // ...
  });
  ....
```
  



```
TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting /..../<path>/index.tsx:1
Rule: "qwik/valid-lexical-scope"
    at Ie (/..../node_modules/eslint-plugin-qwik/index.js:292:1208)
    at Tv (/..../node_modules/eslint-plugin-qwik/index.js:298:1166)
    at Ie (/..../node_modules/eslint-plugin-qwik/index.js:298:1000)
    at Ie (/..../node_modules/eslint-plugin-qwik/index.js:298:97)
    at Tv (/..../node_modules/eslint-plugin-qwik/index.js:298:1166)
    at Ie (/..../node_modules/eslint-plugin-qwik/index.js:298:1000)
    at qv (/..../node_modules/eslint-plugin-qwik/index.js:292:343)
    at Ev (/..../node_modules/eslint-plugin-qwik/index.js:292:194)
    at /..../node_modules/eslint-plugin-qwik/index.js:289:836
    at Array.forEach (<anonymous>) {
  ruleId: 'qwik/valid-lexical-scope',
  currentNode: {
    type: 'Program',
    body: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object]
    ],
    comments: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    range: [ 0, 28196 ],
    sourceType: 'module',
    tokens: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 4564 more items
    ],
    loc: { start: [Object], end: [Object] },
    parent: null
  }
}
```

**Comment by notcod** [comment]
Probably someone fucked up **_eslint-plugin-qwik_** for both errors

**Comment by notcod** [comment]
I found what's causing error in my last message:
https://stackblitz.com/edit/qwik-starter-fmve59?file=src%2Froutes%2Findex.tsx
If I return just string from actions, it throws error
![image](https://github.com/QwikDev/qwik/assets/77313746/bd3b2482-ef5e-4d96-b85b-bbeab2b62662)

**Comment by PatrickJS** [comment]
here's the fix
```jsx

      {head.meta.map((m) => (
        <meta key={m.key} {...m} />
      ))}

      {head.links.map((l) => (
        <link key={l.key} {...l} />
      ))}

      {head.styles.map((s) => (
        <style
          key={s.key}
          {...s.props}
          {...(s.props?.dangerouslySetInnerHTML
            ? {}
            : { dangerouslySetInnerHTML: s.style })}
        />
      ))}

      {head.scripts.map((s) => (
        <script
          key={s.key}
          {...s.props}
          {...(s.props?.dangerouslySetInnerHTML
            ? {}
            : { dangerouslySetInnerHTML: s.script })}
        />
      ))}
    </>
  );
});
```

**Comment by genki** [comment]
This could also solves.
```tsx
      {head.styles.map(({key, style, ...props}) => (
        <style key={key} {...props} dangerouslySetInnerHTML={style} />
      ))}
```
