### ISSUE TITLE
[🫡] fixes for all "Error: Missing Qwik City Env Data"

### ISSUE THREAD

**Issue by PatrickJS** [QwikDev/qwik#6237]
### Suggestion

This is a live thread for different ways to fix `Error: Missing Qwik City Env Data` which can be caused by many different.

**Comment by Nefcanto** [comment]
@PatrickJS, thank you for creating this thread. But I think it's not a good idea to expect developers to memorize the list you presented. The correct way is to give correct messages. Please let me repeat myself:

> The right way is to give correct error messages

That's the first line for troubleshooting and debugging.

**Comment by PatrickJS** [comment]
yes, this is only temporary until we track down each error and fix them. The error itself is triggered more often by other errors which we need to correctly capture

**Comment by seanperez-xyz** [comment]
happens all the time in firefox... if you open up devtools automatically does that

**Comment by seanperez-xyz** [comment]
there was alot of errors before in dev mode that dont pop up anymore... they still do in the console but before there was an error about some image thing that the dev tools injects some container ( it would mess up my css all the time) maybe whatever was done to mute that started throwing this errors ?

**Comment by PatrickJS** [comment]
What's the reproduction? Is it just new qwik app 1.5.5 and open dev mode in Firefox

**Comment by seanperez-xyz** [comment]
> What's the reproduction? Is it just new qwik app 1.5.5 and open dev mode in Firefox

well i just got 1.5.5 and it does the same thing but 15.4 did it do

**Comment by PatrickJS** [comment]
@JerryWu1234 do you have time to look into this bug?

**Comment by JerryWu1234** [comment]
> @JerryWu1234 do you have time to look into this bug?

Ok I can do

**Comment by JerryWu1234** [comment]
![image](https://github.com/QwikDev/qwik/assets/27261522/7c1c67b3-e0b8-4ef5-a1d1-2fc54b4ee8b4)
 everything is fine .
@seanperez-xyz Could you reproduce this bug ?

**Comment by redoPop** [comment]
I just saw another instance of this error triggered when using a hook that returned a single property from a context-bound Store:

```js
export const useFoo = () => {
  const store = useContext(MyContext);
  return store.foo;
};
```

The issue was resolved by abandoning the hook and instead retrieving and destructuring the complete store within components:

```js
const { foo } = useContext(MyContext);
```

**Comment by brunsten** [comment]
I just got it in a new app with 

`node -v
> v18.17.1 

npm create qwik@latest
npx qwik add fastify`

note sure if it was fastify or not.

**Comment by devcaeg** [comment]
Qwik version 1.6 is causing this error to appear constantly in my application.

**Comment by wmertens** [comment]
@devcaeg in dev mode or production? Could you make a repro?

**Comment by 7ojo** [comment]
After upgrading to 1.6 seems I can not also get rid off this. Dev mode.

I have to re-run "npm start" on every change.

**Comment by devcaeg** [comment]
It happens to me in development mode and it is constantly. For the moment I will go back to the previous version, since version 1.6 makes it impossible for me to work.

I will try to make a minimal reproduction of the error so that it can be investigated.

**Comment by wmertens** [comment]
@gioboa I'm also experiencing it but when I revert the assetsDir commit, I don't experience this any more

**Comment by wmertens** [comment]
@gioboa I take that back, it's still broken. Not sure why it worked for a bit.

**Comment by frankroc2022** [comment]
Went back from 1.6 to 1.5.7. If I have no route [...catchall] I get the same error "Missing Qwik City Env Data for help visit https://github.com/QwikDev/qwik/issues/6237" but If I have a [...catchall] route I get this error "TypeError: error loading dynamically imported module: http://localhost:5173/src/components/ts/global_component_4w7djkoecc8.js%3Ft%3D1719875176718". A fresh 1.6 install has not these problems.

**Comment by gioboa** [comment]
> Went back from 1.6 to 1.5.7. If I have no route [...catchall] I get the same error "Missing Qwik City Env Data .....

Can you share with us your repo with the bere minimum stuffs? I would like to face this error because it is so annoying

**Comment by devcaeg** [comment]
@wmertens @gioboa 

I have created a "minimal" reproduction of the problem.

Go to Stackblitz, and navigate between HOME and LOGIN, make some changes to the files and you will see that at various times the error "Missing Qwik City Env Data" will appear.

https://stackblitz.com/edit/qwik-starter-hakacd?file=src%2Froutes%2Flayout.tsx

**Comment by devcaeg** [comment]
Apart from this error, another error "Failed to fetch dynamically imported module" is also being displayed.

**Comment by devcaeg** [comment]
As an extra comment, since version 1.6 inside the "entry.ssr" file using "opts.serverData?.qwikcity?.ev?.sharedMap" sometimes returns "undefiend" in previous versions it never returned "undefiend".

**Comment by gioboa** [comment]
Thanks @devcaeg

**Comment by CristianMR** [comment]
> PS: The way I have been able to reproduce the error, is to navigate a couple of times between HOME and LOGIN, and then change the text of the "Link" and there appears the error.

I'm encountering the same issue. Since version 1.6.0, after making just two or three changes, sometimes with as little as two lines of code, I receive the error message: `Failed to fetch dynamically imported module`. Restarting `npm run dev` temporarily resolves the problem, but it's becoming a nightmare.

**Comment by devcaeg** [comment]
@CristianMR 

For the moment I recommend downgrading to version 1.5.7.

**Comment by sprappcom** [comment]
i just had this issue and i did the CTRL+C to npm start and restart it. then it's gone. using the latest qwik

**Comment by wmertens** [comment]
I'm encountering it when hot reloading. First render, everything is fine, but change some code, and Vite re-runs entry.ssr without providing a request and then the qwik city server data is missing.

Probably the fix is to have module.hot.accept in the right places

**Comment by sprappcom** [comment]
i can "re generate this issue"

simply put this as header.

if you do "
npm run build
"
u'll see the error but u wont see this if u do npm start (which causes the core error etc)

**Comment by devcaeg** [comment]
@sprappcom 

In the meantime use version 1.5.7 instead of 1.6.

**Comment by boris-schwarz** [comment]
I just had the same creating my first Qwik App (1.6). I tried it twice, once with the proposed Default Starter and once with the Empty Starter.

The default starter opened, but there was no interactivity, neither on the very first button, nor on the counter below. However the Alt+Click seemed to work. 

I tried again with the empty starter and adding a dummy counter by myself, for some interaction. 

In both cases I got a js error in the console in the following format:

```
Uncaught (in promise) TypeError: URL constructor: //%40fs/C%3A%5Cprojects%5Cqwik-city-app%5Csrc%5Ccomponents%5Ccounter/counter_component_button_onclick_sefr0m6h0sk.js?_qrl_parent=C%3A%5Cprojects%5Cqwik-city-app%5Csrc%5Ccomponents%5Ccounter%5Ccounter.tsx#Counter_component_button_onClick_seFR0M6H0sk[0] is not a valid URL.
    dispatch http://localhost:5173/:126
    processDocumentEvent http://localhost:5173/:201
    addEventListener http://localhost:5173/:233
    processEventOrNode http://localhost:5173/:241
    processEventOrNode http://localhost:5173/:241
    <anonymous> http://localhost:5173/:264
```

Not sure if it's correct to trying to access my file system instead of http://localhost. I was using Firefox Developer Edition, also tried in Google Chrome with no success.

I tried then to use Qwik 1.5.7 instead of 1.6, and the env error didn't appear again, howevery the error above (URL constructor) still appears in the console and there's no interactivity.

Using Windows 11, Node v20.14.0, Npm 10.4.0, killing the process and running `npm start` unfortunately didn't do the trick.

Maybe those are related, thought I'd let you know.

**Comment by wmertens** [comment]
I think I may have a fix for the situation I explained above, here https://github.com/QwikDev/qwik/pull/6629#issuecomment-2201091318

It makes sure that the vite dev server recognizes qrl segment requests better and doesn't try to SSR them.

**Comment by Nefcanto** [comment]
@wmertens, @gioboa, @PatrickJS , is there a way to show the stack related to the code of us in error?

As I stated above in this thread, the main problem is the lack of information. We don't know why how and where. We have to get into heuristics (trial and error) and restart the app, reboot the system, delete, re-clone, and whatnot.

If you can give us more info on the stack, that would help solve lots of problems.

**Comment by Nefcanto** [comment]
@wmertens, @gioboa, @PatrickJS, based on the stack:

```
12:52:28 PM [vite] Internal server error: Missing Qwik City Env Data for help visit https://github.com/QwikDev/qwik/issues/6237
  File: /npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:3665:22
      at AsyncFunction.QwikCityProvider_component_TxCFOy819ag [as resolved] (/npm/node_modules/@builder.io/qwik-city/index.qwik.mjs:659:11)
      at AsyncFunction.invokeApply (/npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:3665:22)
      at AsyncFunction.invoke (/npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:3658:22)
      at /npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:7297:21
      at maybeThen (/npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:384:54)
      at /npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:7289:25
      at /npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:1043:25
      at safeCall (/npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:373:21)
      at executeComponent (/npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:1043:10)
      at renderSSRComponent (/npm/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:1405:20)
```

I see that the method `executeComponent` is called. Based on that I assume that we have the knowledge of where we are. If you can append that knowledge to the end of this line, it would be very helpful:

> throw new Error(`Missing Qwik City Env Data for help visit https://github.com/QwikDev/qwik/issues/6237`);

**Comment by Nefcanto** [comment]
And when I get that error, I get this error to in my console:

> Loading module from “https://project.local/src/Components/Layout/fixeditems_component_k4eriarhpky.js%3Ft%3D1720357551969” was blocked because of a disallowed MIME type (“text/html”).

And in that file, I have this code:

```


    useOnWindow(
        "scroll",
        $(() => {
            if (window.scrollY > 400) {
                isShownUp.value = true
            } else {
                isShownUp.value = false
            }
        })
    )
```

When I delete this code snippet, then the error goes away.

**Comment by 7ojo** [comment]
Also when looking at network panel I noticed this error "NS_ERROR_CORRUPTED_CONTENT" for this request

`GET http://localhost:5173/node_modules/%40builder.io/qwik-city/link_component_handleprefetch_osdg8fnytw4.js%3Ft%3D1720423501167`

**Comment by wmertens** [comment]
@7ojo that's 1.6.0, we already know that's broken. Please test https://github.com/QwikDev/qwik/pull/6629#issuecomment-2201091318

**Comment by wmertens** [comment]
FYI the 1.6.0 errors are fixed in 1.7.0. This doesn't fix all cases because the message applies to many different errors.

**Comment by boris-schwarz** [comment]
Hey, sorry for the late reply. [My case ](https://github.com/QwikDev/qwik/issues/6237#issuecomment-2209343470) has indeed been fixed with 1.7.0, thanks a lot.

**Comment by devcaeg** [comment]
Now version 1.7 has another error that forces to roll back to version 1.5.7.

Error: TypeError: Failed to fetch dynamically imported module:

**Comment by devcaeg** [comment]
> Now version 1.7 has another error that forces to roll back to version 1.5.7.
> 
> Error: TypeError: Failed to fetch dynamically imported module:

This bug exists since version 1.6, but the other bug in version 1.6 used to appear before this bug. But now in version 1.7, this error appears constantly.

**Comment by frankroc2022** [comment]
I responded here [https://github.com/QwikDev/qwik/pull/6629](url).

**Comment by upayanmazumder** [comment]
Facing the same issue. Check the last commit on this branch https://github.com/upayanmazumder/Pterodactyl-Management-Dashboard/tree/Missing-env-data-issue

**Comment by upayanmazumder** [comment]
> Facing the same issue. Check the last commit on this branch https://github.com/upayanmazumder/Pterodactyl-Management-Dashboard/tree/Missing-env-data-issue

btw the deployment on cf for this branch wont work as it isnt configured to work that way. try to run it locally. my api server is at ```pmdapi.upayan.space```

**Comment by frankroc2022** [comment]
1.7.1 solved all my problems, thx!

**Comment by wmertens** [comment]
@upayanmazumder please minimally reproduce the error with 1.7.1

**Comment by Kampouse** [comment]
@wmertens 
been trying to add stuff into the docs and getting this error frequently within usvisible,usedocument 
https://github.com/QwikDev/qwik/pull/6689

**Comment by yasserlens** [comment]
One more reason this "Error: Missing Qwik City Env Data" appears (took me hours to figure out..):
When an endpoint (onGet, onPost, etc) is defined but isn't returning a response, valid or not.
Here's a minimal reproduction with v1.5.7:
https://stackblitz.com/edit/qwik-starter-3g4hsc?file=src%2Froutes%2Fapi%2Femail-list%2Findex.tsx

The same happens on v1.7.1 - reproduced below:
https://stackblitz.com/edit/qwik-starter-9zkk3z?file=src%2Froutes%2Fapi%2Femail-list%2Findex.tsx

I had no idea what the reason was - until i read somewhere that having an invalid image URL would cause this.

**Comment by shairez** [comment]
@wmertens can you please add the relevant fix context you have?

Thanks

**Comment by maiieul** [comment]
This seems to be related to requesting a bad request in some sort or another.

For example using
```tsx
      <script
        type="speculationrules"
        dangerouslySetInnerHTML={`{"prefetch":[{"urls":["/about/index.html"]}]}`}
      />
```
 will lead to this error.
 
 while 
 ```tsx
       <script
        type="speculationrules"
        dangerouslySetInnerHTML={`{"prefetch":[{"urls":["/about/"]}]}`}
      /> 
```
won't.

MRE: https://github.com/maiieul/qwik-missing-env-data-repro

**Comment by wmertens** [comment]
The most common reason is that SSR is called on a URL that shouldn't be SSR'd.

The SSR handler in qwik city should check the context before rendering

**Comment by JakeAsunto** [comment]
it seems to appear when you delete the **index.tsx** in the same directory as the **root.tsx** file

**Comment by wmertens** [comment]
I added a commit that may expose the problem earlier in dev:

https://github.com/QwikDev/qwik/pull/6825/commits/7e2ce01b5ca5e0c6cf016aa97ce58340d50c03f7

**Comment by Rleslie321** [comment]
I am able to get this bug by opening multiple tabs in chrome and then opening devtools.

MRE:
```
npm create qwik@latest
npm run dev
```
duplicate the localhost tab three times and then open the devtools on the third tab

**Comment by CharlesStover** [comment]
This happens only when I specify a `--host` when running `vite` for dev mode.

**Comment by Nicoleta2891** [comment]
https://github.com/QwikDev/qwik/issues/6237#issue-2279937987

**Comment by gioboa** [comment]
Is there anyone who has still encountered this problem?

**Comment by wmertens** [comment]
Looks like we fixed this, and in V2 the approach is very different, so closing.
