### ISSUE TITLE
[🐞] Qwik doesn't work with NX monorepo

### ISSUE THREAD

**Issue by mhuretski** [QwikDev/qwik#6785]
### Which component is affected?

Qwik Runtime

### Describe the bug

qwik 1.8.0 doesnt work with NX monorepo

### Reproduction

https://github.com/mhuretski/qwik-monorepo

### Steps to reproduce

1. create project `pnpm dlx create-nx-workspace@latest org-workspace --preset=qwik-nx`
2. update qwik to `1.8.0`
3. run project `npx nx run PROJECT_NAME:serve` where PROJECT_NAME - name of the created project 
(in attached repo `npx nx run test:serve`)

```
TypeError: Cannot read properties of undefined (reading 'push')
    at /Users/user/nx-test/node_modules/.pnpm/qwik-nx@2.3.0_@nx+devkit@19.5.7_nx@19.5.7_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+help_ptvdyo345eoikgktw5n5db5a2i/node_modules/qwik-nx/src/plugins/qwik-nx-vite.plugin.js:36:47
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/nx-test/node_modules/.pnpm/tslib@2.6.3/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### System Info

```shell
"dependencies": {
    "qwik-nx": "2.3.0"
  },
  "devDependencies": {
    "@builder.io/qwik": "1.8.0",
    "@builder.io/qwik-city": "1.8.0",
```

### Additional Information

If Qwik is downgraded to `1.7.3` everything works just fine.

**Comment by thejackshelton** [comment]
This has to do with qwik-nx. cc @shairez @dmitry-stepanenko

**Comment by maiieul** [comment]
From what we've seen, you can simply remove the qwikNxVite plugin from now on, qwik natively supports monorepos. @dmitry-stepanenko is working on a release.

**Comment by maiieul** [comment]
Closing because this was fixed a while a go 🙃
