### ISSUE TITLE
Some "Edit this page" links don't work

### ISSUE THREAD

**Issue by maiieul** [QwikDev/qwik#6802]
The urls are constructed based on a hard-coded list of paths:

```tsx
const QWIK_GROUP = [
  'components',
  'concepts',
  'faq',
  'getting-started',
  'think-qwik',
  'deprecated-features',
];

const QWIK_ADVANCED_GROUP = [
  'containers',
  'custom-build-dir',
  'dollar',
  'eslint',
  'library',
  'optimizer',
  'modules-prefetching',
  'qrl',
  'qwikloader',
  'vite',
];

const QWIKCITY_GROUP = [
  'action',
  'api',
  'caching',
  'endpoints',
  'env-variables',
  'guides',
  'html-attributes',
  'layout',
  'middleware',
  'pages',
  'project-structure',
  'qwikcity',
  'route-loader',
  'routing',
  'server$',
  'troubleshooting',
  'validator',
];
const QWIKCITY_ADVANCED_GROUP = [
  'content-security-policy',
  'menu',
  'request-handling',
  'routing',
  'sitemaps',
  'speculative-module-fetching',
  'static-assets',
];
```

We could probably use a menu with useContent hook https://qwik.dev/docs/advanced/menu/#menu.

**Comment by iitzIrFan** [comment]
@maiieul Can I work on this issue ?

**Comment by gioboa** [comment]
@iitzIrFan yep, feel free to drop a PR for this

**Comment by maiieul** [comment]
Yes please, thanks for letting us know 🙏

**Comment by iitzIrFan** [comment]
Can you give me a little description about the work you needed to be done here!

**Comment by iitzIrFan** [comment]
Did you want something like this :- 
![Qwik SS](https://github.com/user-attachments/assets/3d4e3486-54f2-47f9-9c51-5a58bab6b8cf)
Also it gives 404 error whenever I click of the listed items as this project structure is somewhat complex for me but surely am trying to figure it out.
If any changes let me know !

**Comment by iitzIrFan** [comment]
@gioboa @maiieul assign this issue to me so that I cab work on !

**Comment by iitzIrFan** [comment]
@gioboa Thanks for assigning the issue to me. Can you give some details what you want me to work on this issue in detail as there should be no misunderstanding!

**Comment by gioboa** [comment]
Let's wait @maiieul

**Comment by maiieul** [comment]
Thanks @iitzIrFan, the goal is to make sure that all edit this page links work as expected and that it's a maintainable solution. If you can think of a better alternative to useContent, feel free to suggest here or ask on discord docs contributors channel ✌️

**Comment by iitzIrFan** [comment]
@maiieul Will work on it and let you know if any issue!

**Comment by iitzIrFan** [comment]
@maiieul How do I run this project locally on my machine to test and contribute ?

**Comment by maiieul** [comment]
Hmmm, doesn't ‘pnpm docs.dev’ work for you? We have a contributing.md if you haven't read it yet.

**Comment by iitzIrFan** [comment]
Nah this didn't work pnpm docs.dev
And as per this contributing.md, trying to figure it out but no results...
Can you directly tell me the steps for now ?

**Comment by gioboa** [comment]
Can you try to run `pnpm build.local` and then `pnpm docs.dev`?

**Comment by iitzIrFan** [comment]
This was the error I got after using the above mentioned cammand, Any fix ?

51   self.qwikBuild = {
     ~~~~~~~~~~~~~~


Found 1 error in packages/docs/src/repl/worker/repl-dependencies.ts:51


❌ Error: Command failed with exit code 2: tsc -p packages\docs\tsconfig.json
    at makeError (file:///C:/Users/irfan/Downloads/Qwik/qwik/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///C:/Users/irfan/Downloads/Qwik/qwik/node_modules/.pnpm/execa@8.0.1/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async tscDocs (C:\Users\irfan\Downloads\Qwik\qwik\scripts\tsc-docs.ts:8:18)
    at async build (C:\Users\irfan\Downloads\Qwik\qwik\scripts\build.ts:147:7)
 Error: Error: Command failed with exit code 2: tsc -p packages\docs\tsconfig.json
    at makeError (file:///C:/Users/irfan/Downloads/Qwik/qwik/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///C:/Users/irfan/Downloads/Qwik/qwik/node_modules/.pnpm/execa@8.0.1/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async tscDocs (C:\Users\irfan\Downloads\Qwik\qwik\scripts\tsc-docs.ts:8:18)
    at async build (C:\Users\irfan\Downloads\Qwik\qwik\scripts\build.ts:147:7)
    at panic (C:\Users\irfan\Downloads\Qwik\qwik\scripts\util.ts:287:33)
    at build (C:\Users\irfan\Downloads\Qwik\qwik\scripts\build.ts:192:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.

C:\Users\irfan\Downloads\Qwik\qwik>pnpm docs.dev

> qwik-monorepo@0.0.0-read-qwik-package-json docs.dev C:\Users\irfan\Downloads\Qwik\qwik
> cd packages/docs && pnpm build.repl-sw && pnpm dev

cd: no such file or directory: packages/docs
 ELIFECYCLE  Command failed with exit code 1.

**Comment by gioboa** [comment]
Are you using windows?

**Comment by iitzIrFan** [comment]
yes !

**Comment by gioboa** [comment]
> yes !

We have a PR for that #7177
The command should be
`    "docs.dev": "concurrently \"cd packages/docs && pnpm build.repl-sw\" \"cd packages/docs && pnpm dev\"",`

**Comment by iitzIrFan** [comment]
@gioboa Ok it got the project running !

**Comment by iitzIrFan** [comment]
I had gone through the codebase and understood that, I only have to arrange the elements in the array in the structured format and later it would generate respective links when clicked like a loader right ?
If anything that, I missed let me know !

**Comment by maiieul** [comment]
Not sure I understand what you mean by loader here. But yeah I think we should be able to use the menu.md to get the links.

**Comment by iitzIrFan** [comment]
@gioboa @maiieul I had made a PR req to resolve this issue and had also mentioned the changes that, I had made there. Do check & let me know if, any changes are required !
Thank you !

**Comment by iitzIrFan** [comment]
@maiieul @gioboa 

I had viewed this lately that, this PR is closed due to some issue. So now I had fixed it and this time I had done like updated the paths, fixed some special cases that maps to docs and had also made test script to ensure it is working as expected. 

New PR link for review and suggestions :- https://github.com/QwikDev/qwik/pull/7451

**Comment by gioboa** [comment]
Closed by #7451
