### ISSUE TITLE
[🐞] V2 - Promises not expected here

### ISSUE THREAD

**Issue by ianlet** [QwikDev/qwik#7000]
### Which component is affected?

Qwik Runtime

### Describe the bug

Introduced in Qwik V2, the error `Promises not expected here.` is thrown when rendering a component with a conditional projection that is async.

For example:
```tsx
// File: src/routes/index.tsx

export default component$(() => {
  const open = useSignal(false);

  return (
    <TheCursedReveal open={open.value}>
      {t("I am an async string")}
    </TheCursedReveal>
  );
});

const TheCursedReveal = component$<{
  open: boolean;
}>(({ open }) => {
  return <>{open && <Slot />}</>;
});

async function t(key: string): Promise<string> {
  return Promise.resolve(key);
}
```
Any other variants of a `<Slot />` being conditionally rendered will give the same error. For example:
```tsx
const TheOtherCursedReveal = component$<{
  open: boolean;
}>(({ open }) => {
  if (!open) return null;

  return (
    <div>
      <Slot />
    </div>
  );
});
```

Additionally, the error is so obscure that it doesn't help at all to understand where and why this error is triggered:
```
QWIK ERROR Promises not expected here. Error: Promises not expected here.
    at createAndLogError (/home/ian/Projects/noma/node_modules/.pnpm/@builder.io+qwik@file+..+oss+qwik+packages+qwik_prettier@3.3.3_vite@5.4.9_@types+node@22.7.7__3o4nugbb2q2oqnvka6jhcm2faq/node_modules/@builder.io/qwik/dist/core.mjs:53:52)
    at throwErrorAndStop (/home/ian/Projects/noma/node_modules/.pnpm/@builder.io+qwik@file+..+oss+qwik+packages+qwik_prettier@3.3.3_vite@5.4.9_@types+node@22.7.7__3o4nugbb2q2oqnvka6jhcm2faq/node_modules/@builder.io/qwik/dist/core.mjs:28:17)
    at drain (/home/ian/Projects/noma/node_modules/.pnpm/@builder.io+qwik@file+..+oss+qwik+packages+qwik_prettier@3.3.3_vite@5.4.9_@types+node@22.7.7__3o4nugbb2q2oqnvka6jhcm2faq/node_modules/@builder.io/qwik/dist/core.mjs:3202:20)
    at Module._walkJSX (/home/ian/Projects/noma/node_modules/.pnpm/@builder.io+qwik@file+..+oss+qwik+packages+qwik_prettier@3.3.3_vite@5.4.9_@types+node@22.7.7__3o4nugbb2q2oqnvka6jhcm2faq/node_modules/@builder.io/qwik/dist/core.mjs:3226:3)
    at SSRContainer.emitUnclaimedProjection (/home/ian/Projects/noma/node_modules/.pnpm/@builder.io+qwik@file+..+oss+qwik+packages+qwik_prettier@3.3.3_vite@5.4.9_@types+node@22.7.7__3o4nugbb2q2oqnvka6jhcm2faq/node_modules/@builder.io/qwik/dist/server.mjs:8721:35)
    at SSRContainer.emitContainerData (/home/ian/Projects/noma/node_modules/.pnpm/@builder.io+qwik@file+..+oss+qwik+packages+qwik_prettier@3.3.3_vite@5.4.9_@types+node@22.7.7__3o4nugbb2q2oqnvka6jhcm2faq/node_modules/@builder.io/qwik/dist/server.mjs:8414:10)
    at SSRContainer.closeElement (/home/ian/Projects/noma/node_modules/.pnpm/@builder.io+qwik@file+..+oss+qwik+packages+qwik_prettier@3.3.3_vite@5.4.9_@types+node@22.7.7__3o4nugbb2q2oqnvka6jhcm2faq/node_modules/@builder.io/qwik/dist/server.mjs:8239:24)
    at drain (/home/ian/Projects/noma/node_modules/.pnpm/@builder.io+qwik@file+..+oss+qwik+packages+qwik_prettier@3.3.3_vite@5.4.9_@types+node@22.7.7__3o4nugbb2q2oqnvka6jhcm2faq/node_modules/@builder.io/qwik/dist/core.mjs:3207:31)
    at resolveValue (/home/ian/Projects/noma/node_modules/.pnpm/@builder.io+qwik@file+..+oss+qwik+packages+qwik_prettier@3.3.3_vite@5.4.9_@types+node@22.7.7__3o4nugbb2q2oqnvka6jhcm2faq/node_modules/@builder.io/qwik/dist/core.mjs:3189:5)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
```

### Additional Information

Debugging:
- We're hitting this branch https://github.com/QwikDev/qwik/blob/build/v2/packages/qwik/src/server/ssr-container.ts#L927
- where we explicitly disallow promises as shown here https://github.com/QwikDev/qwik/blob/build/v2/packages/qwik/src/server/ssr-container.ts#L946
- then the error is thrown around here https://github.com/QwikDev/qwik/blob/build/v2/packages/qwik/src/core/ssr/ssr-render-jsx.ts#L101

**Comment by Varixo** [comment]
Nice catch! Thank you for the reproduction 😄 Should be fixed now
