### ISSUE TITLE
[🐞]npm dev error  ReadableStream is not defined

### ISSUE THREAD

**Issue by TeresaMini** [QwikDev/qwik#7169]
### Which component is affected?

Starters / CLI

### Describe the bug

1. node 16
2. npm create qwik@latest
3. npm install
4. npm start
报错
└─[0] npm start  

> start
> vite --open --mode ssr

failed to load config from /Users/zhangxuejie03/Desktop/test/qwik-app/vite.config.ts
error when starting dev server:
ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/Users/zhangxuejie03/Desktop/test/qwik-app/node_modules/undici/lib/web/fetch/webidl.js:471:58)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/zhangxuejie03/Desktop/test/qwik-app/node_modules/undici/lib/web/fetch/util.js:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)

### Reproduction

暂无

### Steps to reproduce

同上

### System Info

```shell
npx envinfo --system --npmPackages '{vite,undici,typescript,@builder.io/*}' --binaries --browsers
Need to install the following packages:
  envinfo@7.14.0
Ok to proceed? (y) y

  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 69.48 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 6.35.1 - ~/.nvm/versions/node/v16.20.2/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 17.5
  npmPackages:
    @builder.io/qwik: ^1.11.0 => 1.11.0 
    @builder.io/qwik-city: ^1.11.0 => 1.11.0 
    typescript: 5.4.5 => 5.4.5 
    undici: * => 7.1.0 
    vite: 5.3.5 => 5.3.5
```

**Comment by gioboa** [comment]
HI @TeresaMini thanks for your feedback, can you try with a recent version of Node please?

**Comment by TeresaMini** [comment]
> HI @TeresaMini thanks for your feedback, can you try with a recent version of Node please?

nice , i use node 23 and it works, thank you
